import './admin-user';
import './profile-edit-profile';
import './profile-edit-password';import './faq';
import './post';
import './category';
import './customer';
import './customers-history';
import './customer-prescription';
import './medicine';
import './posts-comment';
import './customers-prescription';
